//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace EarlyXrm
{
	using System;
	using System.Linq;
	using Microsoft.Xrm.Sdk;
	using System.Runtime.Serialization;
	using Microsoft.Xrm.Sdk.Client;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Diagnostics.CodeAnalysis;
	
	
	[DataContractAttribute()]
	[EntityLogicalNameAttribute("solution")]
	[ExcludeFromCodeCoverage()]
	public partial class Solution : EarlyEntity
	{
		
		public Solution() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "solution";
		
		public const string EntityLogicalCollectionName = "solutions";
		
		public const string EntitySetName = "solutions";
		
		[AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return GetAttributeValue<System.String>("description");
			}
			set
			{
				SetAttributeValue("description", nameof(Description), value);
			}
		}
		
		[AttributeLogicalNameAttribute("friendlyname")]
		public string FriendlyName
		{
			get
			{
				return GetAttributeValue<System.String>("friendlyname");
			}
			set
			{
				SetAttributeValue("friendlyname", nameof(FriendlyName), value);
			}
		}
		
		[AttributeLogicalNameAttribute("installedon")]
		public DateTime? InstalledOn
		{
			get
			{
				return GetAttributeValue<DateTime?>("installedon");
			}
			set
			{
				SetAttributeValue("installedon", nameof(InstalledOn), value);
			}
		}
		
		[AttributeLogicalNameAttribute("ismanaged")]
		public bool? IsManaged
		{
			get
			{
				return GetAttributeValue<bool?>("ismanaged");
			}
			set
			{
				SetAttributeValue("ismanaged", nameof(IsManaged), value);
			}
		}
		
		[AttributeLogicalNameAttribute("isvisible")]
		public bool? IsVisible
		{
			get
			{
				return GetAttributeValue<bool?>("isvisible");
			}
			set
			{
				SetAttributeValue("isvisible", nameof(IsVisible), value);
			}
		}
		
		[AttributeLogicalNameAttribute("organizationid")]
		public EntityReference OrganizationId
		{
			get
			{
				return GetAttributeValue<EntityReference>("organizationid");
			}
			set
			{
				SetAttributeValue("organizationid", nameof(OrganizationId), value);
			}
		}
		
		[AttributeLogicalNameAttribute("parentsolutionid")]
		public EntityReference ParentSolutionId
		{
			get
			{
				return GetAttributeValue<EntityReference>("parentsolutionid");
			}
			set
			{
				SetAttributeValue("parentsolutionid", nameof(ParentSolutionId), value);
			}
		}
		
		[AttributeLogicalNameAttribute("pinpointsolutiondefaultlocale")]
		public string PinpointSolutionDefaultLocale
		{
			get
			{
				return GetAttributeValue<System.String>("pinpointsolutiondefaultlocale");
			}
			set
			{
				SetAttributeValue("pinpointsolutiondefaultlocale", nameof(PinpointSolutionDefaultLocale), value);
			}
		}
		
		[AttributeLogicalNameAttribute("publisherid")]
		public EntityReference PublisherId
		{
			get
			{
				return GetAttributeValue<EntityReference>("publisherid");
			}
			set
			{
				SetAttributeValue("publisherid", nameof(PublisherId), value);
			}
		}
		
		[AttributeLogicalNameAttribute("solutionid")]
		public new virtual Guid Id
		{
			get
			{
				return base.Id != default ? base.Id : GetAttributeValue<Guid>("solutionid");
			}
			set
			{
				SetAttributeValue("solutionid", nameof(Id), value);
				base.Id = value;
			}
		}
		
		[AttributeLogicalNameAttribute("solutionpackageversion")]
		public string SolutionPackageVersion
		{
			get
			{
				return GetAttributeValue<System.String>("solutionpackageversion");
			}
			set
			{
				SetAttributeValue("solutionpackageversion", nameof(SolutionPackageVersion), value);
			}
		}
		
		[AttributeLogicalNameAttribute("solutiontype")]
		public solution_solutiontype? SolutionType
		{
			get
			{
				return (solution_solutiontype?)GetAttributeValue<OptionSetValue>("solutiontype")?.Value;
			}
			set
			{
				SetAttributeValue("solutiontype", nameof(SolutionType), value.HasValue ? new OptionSetValue((int)value.Value) : null);
			}
		}
		
		[AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return GetAttributeValue<System.String>("uniquename");
			}
			set
			{
				SetAttributeValue("uniquename", nameof(UniqueName), value);
			}
		}
		
		[AttributeLogicalNameAttribute("updatedon")]
		public DateTime? UpdatedOn
		{
			get
			{
				return GetAttributeValue<DateTime?>("updatedon");
			}
			set
			{
				SetAttributeValue("updatedon", nameof(UpdatedOn), value);
			}
		}
		
		[AttributeLogicalNameAttribute("version")]
		public string Version
		{
			get
			{
				return GetAttributeValue<System.String>("version");
			}
			set
			{
				SetAttributeValue("version", nameof(Version), value);
			}
		}
		
		[AttributeLogicalNameAttribute("versionnumber")]
		public long? VersionNumber
		{
			get
			{
				return GetAttributeValue<long?>("versionnumber");
			}
			set
			{
				SetAttributeValue("versionnumber", nameof(VersionNumber), value);
			}
		}
		
		[RelationshipSchemaNameAttribute("solution_parent_solution", EntityRole.Referenced)]
		public IEnumerable<Solution> Referencedsolution_parent_solution
		{
			get
			{
				return GetRelatedEntities<Solution>("solution_parent_solution", EntityRole.Referenced);
			}
			set
			{
				SetRelatedEntities<Solution>("solution_parent_solution", nameof(Referencedsolution_parent_solution), value, EntityRole.Referenced);
			}
		}
		
		[RelationshipSchemaNameAttribute("solution_solutioncomponent")]
		public IEnumerable<SolutionComponent> solution_solutioncomponent
		{
			get
			{
				return GetRelatedEntities<SolutionComponent>("solution_solutioncomponent");
			}
			set
			{
				SetRelatedEntities<SolutionComponent>("solution_solutioncomponent", nameof(solution_solutioncomponent), value);
			}
		}
		
		[AttributeLogicalNameAttribute("parentsolutionid")]
		[RelationshipSchemaNameAttribute("solution_parent_solution", EntityRole.Referencing)]
		public Solution Referencingsolution_parent_solution
		{
			get
			{
				return GetRelatedEntity<Solution>("solution_parent_solution", EntityRole.Referencing);
			}
		}
		
		[DataContract()]
		public class LogicalNames
		{
			
			public static string Description = "description";
			
			public static string FriendlyName = "friendlyname";
			
			public static string InstalledOn = "installedon";
			
			public static string IsManaged = "ismanaged";
			
			public static string IsVisible = "isvisible";
			
			public static string OrganizationId = "organizationid";
			
			public static string ParentSolutionId = "parentsolutionid";
			
			public static string PinpointSolutionDefaultLocale = "pinpointsolutiondefaultlocale";
			
			public static string PublisherId = "publisherid";
			
			public static string Id = "solutionid";
			
			public static string SolutionPackageVersion = "solutionpackageversion";
			
			public static string SolutionType = "solutiontype";
			
			public static string UniqueName = "uniquename";
			
			public static string UpdatedOn = "updatedon";
			
			public static string Version = "version";
			
			public static string VersionNumber = "versionnumber";
			
			public static string Referencingsolution_parent_solution = "parentsolutionid";
		}
		
		[DataContract()]
		public class Relationships
		{
			
			public static string Referencedsolution_parent_solution = "solution_parent_solution";
			
			public static string solution_solutioncomponent = "solution_solutioncomponent";
			
			public static string Referencingsolution_parent_solution = "solution_parent_solution";
		}
	}
	
	[DataContractAttribute()]
	[EntityLogicalNameAttribute("solutioncomponent")]
	[ExcludeFromCodeCoverage()]
	public partial class SolutionComponent : EarlyEntity
	{
		
		public SolutionComponent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "solutioncomponent";
		
		public const string EntityLogicalCollectionName = "solutioncomponentss";
		
		public const string EntitySetName = "solutioncomponents";
		
		[AttributeLogicalNameAttribute("componenttype")]
		public componenttype? ComponentType
		{
			get
			{
				return (componenttype?)GetAttributeValue<OptionSetValue>("componenttype")?.Value;
			}
			set
			{
				SetAttributeValue("componenttype", nameof(ComponentType), value.HasValue ? new OptionSetValue((int)value.Value) : null);
			}
		}
		
		[AttributeLogicalNameAttribute("objectid")]
		public Guid? ObjectId
		{
			get
			{
				return GetAttributeValue<Guid?>("objectid");
			}
			set
			{
				SetAttributeValue("objectid", nameof(ObjectId), value);
			}
		}
		
		[AttributeLogicalNameAttribute("rootcomponentbehavior")]
		public solutioncomponent_rootcomponentbehavior? RootComponentBehavior
		{
			get
			{
				return (solutioncomponent_rootcomponentbehavior?)GetAttributeValue<OptionSetValue>("rootcomponentbehavior")?.Value;
			}
			set
			{
				SetAttributeValue("rootcomponentbehavior", nameof(RootComponentBehavior), value.HasValue ? new OptionSetValue((int)value.Value) : null);
			}
		}
		
		[AttributeLogicalNameAttribute("solutioncomponentid")]
		public new virtual Guid Id
		{
			get
			{
				return base.Id != default ? base.Id : GetAttributeValue<Guid>("solutioncomponentid");
			}
			set
			{
				SetAttributeValue("solutioncomponentid", nameof(Id), value);
				base.Id = value;
			}
		}
		
		[AttributeLogicalNameAttribute("solutionid")]
		public EntityReference SolutionId
		{
			get
			{
				return GetAttributeValue<EntityReference>("solutionid");
			}
			set
			{
				SetAttributeValue("solutionid", nameof(SolutionId), value);
			}
		}
		
		[AttributeLogicalNameAttribute("solutionid")]
		[RelationshipSchemaNameAttribute("solution_solutioncomponent")]
		public Solution solution_solutioncomponent
		{
			get
			{
				return GetRelatedEntity<Solution>("solution_solutioncomponent");
			}
		}
		
		[DataContract()]
		public class LogicalNames
		{
			
			public static string ComponentType = "componenttype";
			
			public static string ObjectId = "objectid";
			
			public static string RootComponentBehavior = "rootcomponentbehavior";
			
			public static string Id = "solutioncomponentid";
			
			public static string SolutionId = "solutionid";
			
			public static string solution_solutioncomponent = "solutionid";
		}
		
		[DataContract()]
		public class Relationships
		{
			
			public static string solution_solutioncomponent = "solution_solutioncomponent";
		}
	}
	
	[DataContract()]
	public class EarlyEntity : Entity, INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		public EarlyEntity(string entityLogicalName) : base(entityLogicalName) { }
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected void OnPropertyChanged(string propertyName)
        {
            if ((PropertyChanged != null))
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
		
		protected void OnPropertyChanging(string propertyName)
        {
            if ((PropertyChanging != null))
            {
                PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
            }
        }
		
		public IEnumerable<T> GetAttributeValues<T>(string attributeLogicalName) where T : Entity
	    {
		    return base.GetAttributeValue<EntityCollection>(attributeLogicalName)?.Entities?.Cast<T>();
	    }
		
		protected void SetAttributeValues<T>(string logicalName, string attributePropertyName, IEnumerable<T> value)  where T : Entity
        {
            SetAttributeValue(logicalName, attributePropertyName, new EntityCollection(new List<Entity>(value)));
        }
		
		protected void SetAttributeValue(string logicalName, string attributePropertyName, object value)
        {
            OnPropertyChanging(attributePropertyName);
            base.SetAttributeValue(logicalName, value);
            OnPropertyChanged(attributePropertyName);
        }
		
		protected new T GetRelatedEntity<T>(string relationshipSchemaName, EntityRole? primaryEntityRole = null) where T : Entity
        {
            return base.GetRelatedEntity<T>(relationshipSchemaName, primaryEntityRole);
        }
		
		protected void SetRelatedEntity<T>(string relationshipSchemaName, string attributePropertyName, T entity, EntityRole? primaryEntityRole = null) where T : Entity
        {
            OnPropertyChanging(attributePropertyName);
            base.SetRelatedEntity(relationshipSchemaName, primaryEntityRole, entity);
            OnPropertyChanged(attributePropertyName);
        }
		
		protected new IEnumerable<T> GetRelatedEntities<T>(string relationshipSchemaName, EntityRole? primaryEntityRole = null) where T : Entity
        {
            return base.GetRelatedEntities<T>(relationshipSchemaName, primaryEntityRole);
        }
		
		protected void SetRelatedEntities<T>(string relationshipSchemaName, string attributePropertyName, IEnumerable<T> entities, EntityRole? primaryEntityRole = null) where T : Entity
        {
            OnPropertyChanging(attributePropertyName);
            base.SetRelatedEntities(relationshipSchemaName, primaryEntityRole, entities);
            OnPropertyChanged(attributePropertyName);
        }
	}
}
