//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarlyXrm
{
	using System.Runtime.Serialization;
	using System.ComponentModel;
	
	
	[DataContract()]
	public enum componenttype
	{
		
		[Description("Entity")]
		[EnumMember()]
		Entity = 1,
		
		[Description("Attribute")]
		[EnumMember()]
		Attribute = 2,
		
		[Description("Relationship")]
		[EnumMember()]
		Relationship = 3,
		
		[Description("Attribute Picklist Value")]
		[EnumMember()]
		AttributePicklistValue = 4,
		
		[Description("Attribute Lookup Value")]
		[EnumMember()]
		AttributeLookupValue = 5,
		
		[Description("View Attribute")]
		[EnumMember()]
		ViewAttribute = 6,
		
		[Description("Localized Label")]
		[EnumMember()]
		LocalizedLabel = 7,
		
		[Description("Relationship Extra Condition")]
		[EnumMember()]
		RelationshipExtraCondition = 8,
		
		[Description("Option Set")]
		[EnumMember()]
		OptionSet = 9,
		
		[Description("Entity Relationship")]
		[EnumMember()]
		EntityRelationship = 10,
		
		[Description("Entity Relationship Role")]
		[EnumMember()]
		EntityRelationshipRole = 11,
		
		[Description("Entity Relationship Relationships")]
		[EnumMember()]
		EntityRelationshipRelationships = 12,
		
		[Description("Managed Property")]
		[EnumMember()]
		ManagedProperty = 13,
		
		[Description("Entity Key")]
		[EnumMember()]
		EntityKey = 14,
		
		[Description("Privilege")]
		[EnumMember()]
		Privilege = 16,
		
		[Description("PrivilegeObjectTypeCode")]
		[EnumMember()]
		PrivilegeObjectTypeCode = 17,
		
		[Description("Role")]
		[EnumMember()]
		Role = 20,
		
		[Description("Role Privilege")]
		[EnumMember()]
		RolePrivilege = 21,
		
		[Description("Display String")]
		[EnumMember()]
		DisplayString = 22,
		
		[Description("Display String Map")]
		[EnumMember()]
		DisplayStringMap = 23,
		
		[Description("Form")]
		[EnumMember()]
		Form = 24,
		
		[Description("Organization")]
		[EnumMember()]
		Organization = 25,
		
		[Description("Saved Query")]
		[EnumMember()]
		SavedQuery = 26,
		
		[Description("Workflow")]
		[EnumMember()]
		Workflow = 29,
		
		[Description("Report")]
		[EnumMember()]
		Report = 31,
		
		[Description("Report Entity")]
		[EnumMember()]
		ReportEntity = 32,
		
		[Description("Report Category")]
		[EnumMember()]
		ReportCategory = 33,
		
		[Description("Report Visibility")]
		[EnumMember()]
		ReportVisibility = 34,
		
		[Description("Attachment")]
		[EnumMember()]
		Attachment = 35,
		
		[Description("Email Template")]
		[EnumMember()]
		EmailTemplate = 36,
		
		[Description("Contract Template")]
		[EnumMember()]
		ContractTemplate = 37,
		
		[Description("KB Article Template")]
		[EnumMember()]
		KBArticleTemplate = 38,
		
		[Description("Mail Merge Template")]
		[EnumMember()]
		MailMergeTemplate = 39,
		
		[Description("Duplicate Rule")]
		[EnumMember()]
		DuplicateRule = 44,
		
		[Description("Duplicate Rule Condition")]
		[EnumMember()]
		DuplicateRuleCondition = 45,
		
		[Description("Entity Map")]
		[EnumMember()]
		EntityMap = 46,
		
		[Description("Attribute Map")]
		[EnumMember()]
		AttributeMap = 47,
		
		[Description("Ribbon Command")]
		[EnumMember()]
		RibbonCommand = 48,
		
		[Description("Ribbon Context Group")]
		[EnumMember()]
		RibbonContextGroup = 49,
		
		[Description("Ribbon Customization")]
		[EnumMember()]
		RibbonCustomization = 50,
		
		[Description("Ribbon Rule")]
		[EnumMember()]
		RibbonRule = 52,
		
		[Description("Ribbon Tab To Command Map")]
		[EnumMember()]
		RibbonTabToCommandMap = 53,
		
		[Description("Ribbon Diff")]
		[EnumMember()]
		RibbonDiff = 55,
		
		[Description("Saved Query Visualization")]
		[EnumMember()]
		SavedQueryVisualization = 59,
		
		[Description("System Form")]
		[EnumMember()]
		SystemForm = 60,
		
		[Description("Web Resource")]
		[EnumMember()]
		WebResource = 61,
		
		[Description("Site Map")]
		[EnumMember()]
		SiteMap = 62,
		
		[Description("Connection Role")]
		[EnumMember()]
		ConnectionRole = 63,
		
		[Description("Complex Control")]
		[EnumMember()]
		ComplexControl = 64,
		
		[Description("Field Security Profile")]
		[EnumMember()]
		FieldSecurityProfile = 70,
		
		[Description("Field Permission")]
		[EnumMember()]
		FieldPermission = 71,
		
		[Description("Plugin Type")]
		[EnumMember()]
		PluginType = 90,
		
		[Description("Plugin Assembly")]
		[EnumMember()]
		PluginAssembly = 91,
		
		[Description("SDK Message Processing Step")]
		[EnumMember()]
		SDKMessageProcessingStep = 92,
		
		[Description("SDK Message Processing Step Image")]
		[EnumMember()]
		SDKMessageProcessingStepImage = 93,
		
		[Description("Service Endpoint")]
		[EnumMember()]
		ServiceEndpoint = 95,
		
		[Description("Routing Rule")]
		[EnumMember()]
		RoutingRule = 150,
		
		[Description("Routing Rule Item")]
		[EnumMember()]
		RoutingRuleItem = 151,
		
		[Description("SLA")]
		[EnumMember()]
		SLA = 152,
		
		[Description("SLA Item")]
		[EnumMember()]
		SLAItem = 153,
		
		[Description("Convert Rule")]
		[EnumMember()]
		ConvertRule = 154,
		
		[Description("Convert Rule Item")]
		[EnumMember()]
		ConvertRuleItem = 155,
		
		[Description("Hierarchy Rule")]
		[EnumMember()]
		HierarchyRule = 65,
		
		[Description("Mobile Offline Profile")]
		[EnumMember()]
		MobileOfflineProfile = 161,
		
		[Description("Mobile Offline Profile Item")]
		[EnumMember()]
		MobileOfflineProfileItem = 162,
		
		[Description("Similarity Rule")]
		[EnumMember()]
		SimilarityRule = 165,
		
		[Description("Custom Control")]
		[EnumMember()]
		CustomControl = 66,
		
		[Description("Custom Control Default Config")]
		[EnumMember()]
		CustomControlDefaultConfig = 68,
		
		[Description("Data Source Mapping")]
		[EnumMember()]
		DataSourceMapping = 166,
		
		[Description("SDKMessage")]
		[EnumMember()]
		SDKMessage = 201,
		
		[Description("SDKMessageFilter")]
		[EnumMember()]
		SDKMessageFilter = 202,
		
		[Description("SdkMessagePair")]
		[EnumMember()]
		SdkMessagePair = 203,
		
		[Description("SdkMessageRequest")]
		[EnumMember()]
		SdkMessageRequest = 204,
		
		[Description("SdkMessageRequestField")]
		[EnumMember()]
		SdkMessageRequestField = 205,
		
		[Description("SdkMessageResponse")]
		[EnumMember()]
		SdkMessageResponse = 206,
		
		[Description("SdkMessageResponseField")]
		[EnumMember()]
		SdkMessageResponseField = 207,
		
		[Description("WebWizard")]
		[EnumMember()]
		WebWizard = 210,
		
		[Description("Index")]
		[EnumMember()]
		Index = 18,
		
		[Description("Import Map")]
		[EnumMember()]
		ImportMap = 208,
		
		[Description("Canvas App")]
		[EnumMember()]
		CanvasApp = 300,
		
		[Description("Connector")]
		[EnumMember()]
		Connector = 371,
		
		[Description("Connector")]
		[EnumMember()]
		Connector2 = 372,
		
		[Description("Environment Variable Definition")]
		[EnumMember()]
		EnvironmentVariableDefinition = 380,
		
		[Description("Environment Variable Value")]
		[EnumMember()]
		EnvironmentVariableValue = 381,
		
		[Description("AI Project Type")]
		[EnumMember()]
		AIProjectType = 400,
		
		[Description("AI Project")]
		[EnumMember()]
		AIProject = 401,
		
		[Description("AI Configuration")]
		[EnumMember()]
		AIConfiguration = 402,
		
		[Description("Entity Analytics Configuration")]
		[EnumMember()]
		EntityAnalyticsConfiguration = 430,
		
		[Description("Attribute Image Configuration")]
		[EnumMember()]
		AttributeImageConfiguration = 431,
		
		[Description("Entity Image Configuration")]
		[EnumMember()]
		EntityImageConfiguration = 432,
	}
	
	[DataContract()]
	public enum solution_solutiontype
	{
		
		[Description("None")]
		[EnumMember()]
		None = 0,
		
		[Description("Snapshot")]
		[EnumMember()]
		Snapshot = 1,
		
		[Description("Internal")]
		[EnumMember()]
		Internal = 2,
	}
	
	[DataContract()]
	public enum solutioncomponent_rootcomponentbehavior
	{
		
		[Description("Include Subcomponents")]
		[EnumMember()]
		IncludeSubcomponents = 0,
		
		[Description("Do not include subcomponents")]
		[EnumMember()]
		DoNotIncludeSubcomponents = 1,
		
		[Description("Include As Shell Only")]
		[EnumMember()]
		IncludeAsShellOnly = 2,
	}
}
