//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace EarlyBoundSolutionGenerator
{


	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum crb60_contacttype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Applicant = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SPOC = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Employer = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum crb60_cattype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Black = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Grey = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		White = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum goal_fiscalperiod
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter1 = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter2 = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter3 = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter4 = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 101,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 102,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 103,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 104,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 105,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 106,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 107,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 108,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 109,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 110,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 111,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 112,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semester1 = 201,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semester2 = 202,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Annual = 301,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P1 = 401,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P2 = 402,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P3 = 403,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P4 = 404,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P5 = 405,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P6 = 406,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P7 = 407,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P8 = 408,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P9 = 409,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P10 = 410,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P11 = 411,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P12 = 412,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		P13 = 413,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum goal_fiscalyear
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2038 = 2038,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2037 = 2037,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2036 = 2036,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2035 = 2035,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2034 = 2034,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2033 = 2033,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2032 = 2032,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2031 = 2031,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2030 = 2030,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2029 = 2029,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2028 = 2028,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2027 = 2027,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2026 = 2026,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2025 = 2025,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2024 = 2024,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2023 = 2023,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2022 = 2022,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2021 = 2021,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2020 = 2020,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2019 = 2019,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2018 = 2018,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2017 = 2017,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2016 = 2016,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2015 = 2015,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2014 = 2014,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2013 = 2013,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2012 = 2012,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2011 = 2011,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2010 = 2010,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2009 = 2009,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2008 = 2008,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2007 = 2007,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2006 = 2006,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2005 = 2005,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2004 = 2004,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2003 = 2003,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2002 = 2002,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2001 = 2001,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2000 = 2000,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1999 = 1999,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1998 = 1998,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1997 = 1997,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1996 = 1996,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1995 = 1995,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1994 = 1994,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1993 = 1993,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1992 = 1992,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1991 = 1991,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1990 = 1990,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1989 = 1989,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1988 = 1988,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1987 = 1987,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1986 = 1986,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1985 = 1985,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1984 = 1984,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1983 = 1983,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1982 = 1982,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1981 = 1981,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1980 = 1980,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1979 = 1979,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1978 = 1978,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1977 = 1977,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1976 = 1976,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1975 = 1975,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1974 = 1974,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1973 = 1973,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1972 = 1972,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1971 = 1971,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1970 = 1970,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum metric_goaltype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Money = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Decimal = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Integer = 2,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum componentstate
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletedUnpublished = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum workflowlog_objecttypecode
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemJob = 4700,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkflowSession = 4710,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlowSession = 4720,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum connectionrole_category
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Business = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Family = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Social = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sales = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Stakeholder = 1000,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesTeam = 1001,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 1002,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum isinherited
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamprivilegesonly = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectUser_BasicaccesslevelandTeamprivileges = 1,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum connectortype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomConnector = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSpecified = 0,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum orginsightsconfiguration_plotoption
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Line = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Column = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Area = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pie = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bar = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donut = 6,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Infocard = 7,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		List = 8,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoubleDonut = 9,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinearGauge = 10,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bubble = 11,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum sharepointdocumentlocation_locationtype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		General = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DedicatedforOneNoteIntegration = 1,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum activitypointer_deliveryprioritycode
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 2,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum msdyn_connectortype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomConnector = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSpecified = 0,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum sla_slaenabledentities
	{
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum componenttype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attribute = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relationship = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributePicklistValue = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeLookupValue = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ViewAttribute = 6,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocalizedLabel = 7,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipExtraCondition = 8,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionSet = 9,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationship = 10,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationshipRole = 11,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationshipRelationships = 12,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagedProperty = 13,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityKey = 14,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Privilege = 16,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivilegeObjectTypeCode = 17,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Role = 20,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RolePrivilege = 21,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayString = 22,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayStringMap = 23,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 24,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 25,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedQuery = 26,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 29,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Report = 31,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportEntity = 32,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportCategory = 33,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportVisibility = 34,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 35,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailTemplate = 36,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContractTemplate = 37,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		KBArticleTemplate = 38,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailMergeTemplate = 39,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRule = 44,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRuleCondition = 45,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityMap = 46,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeMap = 47,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCommand = 48,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonContextGroup = 49,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCustomization = 50,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonRule = 52,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonTabToCommandMap = 53,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonDiff = 55,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedQueryVisualization = 59,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemForm = 60,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebResource = 61,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SiteMap = 62,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 63,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ComplexControl = 64,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldSecurityProfile = 70,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldPermission = 71,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginType = 90,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginAssembly = 91,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageProcessingStep = 92,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageProcessingStepImage = 93,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceEndpoint = 95,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRule = 150,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRuleItem = 151,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLA = 152,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAItem = 153,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertRule = 154,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertRuleItem = 155,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		HierarchyRule = 65,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfile = 161,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfileItem = 162,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SimilarityRule = 165,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControl = 66,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControlDefaultConfig = 68,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataSourceMapping = 166,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessage = 201,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageFilter = 202,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessagePair = 203,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequest = 204,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequestField = 205,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponse = 206,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponseField = 207,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebWizard = 210,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Index = 18,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportMap = 208,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanvasApp = 300,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connector371 = 371,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connector = 372,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariableDefinition = 380,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariableValue = 381,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIProjectType = 400,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIProject = 401,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIConfiguration = 402,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAnalyticsConfiguration = 430,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeImageConfiguration = 431,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityImageConfiguration = 432,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum activitypointer_activitytypecode
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donation = 10007,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum workflow_runas
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallingUser = 1,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum delete_recurringappointmentmaster
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allinstances = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theseriesleavepastappointments = 2,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum orginsightsconfiguration_lookback
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_2H = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_48H = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_7D = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_30D = 4,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum sharepoint_validationstatus
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotValidated = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalid = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Valid = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Couldnotvalidate = 5,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum emailserverprofile_authenticationprotocol
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutoDetect = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Negotiate = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		NTLM = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basic = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		OAuth = 4,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum sharepointsite_servicetype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharePoint = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		OneDrive = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sharedwithme = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		MSTeams = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum mobileofflineenabledentities
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 1001,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum convertrule_channelactivity
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donation = 10007,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum selectedmobileofflineenabledentityrelationships
	{
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum knowledgearticle_expirationstate
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Expired = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Archived = 5,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum socialactivity_postmessagetype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublicMessage = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivateMessage = 1,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum syncattributemapping_syncdirection
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToExchange = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToCRM = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bidirectional = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum workflow_stage
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preoperation = 20,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postoperation = 40,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum dependencytype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionInternal = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 4,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum bulkemail_recipients
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Selectedrecordsoncurrentpage = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allrecordsoncurrentpage = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allrecordsonallpages = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum socialprofile_community
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 0,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum field_security_permission_type
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotAllowed = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allowed = 4,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum photo_resolution
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceDefault = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_640x480 = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_1024x768 = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_1600x1200 = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_2048x1536 = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number_2592x1936 = 5,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum flipswitch_options
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Off = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		On = 1,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum processstage_category
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 6,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approval = 7,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum sharepoint_validationstatusreason
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLhasnotbeenvalidated = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLisvalid = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLisnotvalid = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheURLschemesofMicrosoftDynamics365andSharePointaredifferent = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheURLcouldnotbeaccessedbecauseofInternetExplorersecuritysettings = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Authenticationfailure = 6,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalidcertificates = 7,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum recurrencerule_monthofyear
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidMonthOfYear = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 6,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 7,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 8,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 9,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 10,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 11,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 12,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum principalsyncattributemapping_syncdirection
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToExchange = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToCRM = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bidirectional = 3,
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum solution_solutiontype
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Snapshot = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = 2,
	}

	/// <summary>
	/// A solution which contains CRM customizations.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("solution")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class Solution : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{

		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Solution() :
				base(EntityLogicalName)
		{
		}

		public const string EntityLogicalName = "solution";

		public const int EntityTypeCode = 7100;

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}

		/// <summary>
		/// A link to an optional configuration page for this solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("configurationpageid")]
		public Microsoft.Xrm.Sdk.EntityReference ConfigurationPageId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("configurationpageid");
			}
			set
			{
				this.OnPropertyChanging("ConfigurationPageId");
				this.SetAttributeValue("configurationpageid", value);
				this.OnPropertyChanged("ConfigurationPageId");
			}
		}

		/// <summary>
		/// Unique identifier of the user who created the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}

		/// <summary>
		/// Date and time when the solution was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}

		/// <summary>
		/// Unique identifier of the delegate user who created the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}

		/// <summary>
		/// Description of the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}

		/// <summary>
		/// User display name for the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("friendlyname")]
		public string FriendlyName
		{
			get
			{
				return this.GetAttributeValue<string>("friendlyname");
			}
			set
			{
				this.OnPropertyChanging("FriendlyName");
				this.SetAttributeValue("friendlyname", value);
				this.OnPropertyChanged("FriendlyName");
			}
		}

		/// <summary>
		/// Date and time when the solution was installed/upgraded.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("installedon")]
		public System.Nullable<System.DateTime> InstalledOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("installedon");
			}
		}

		/// <summary>
		/// Information about whether the solution is api managed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isapimanaged")]
		public System.Nullable<bool> IsApiManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isapimanaged");
			}
		}

		/// <summary>
		/// Indicates whether the solution is managed or unmanaged.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}

		/// <summary>
		/// Indicates whether the solution is visible outside of the platform.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isvisible")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isvisible");
			}
		}

		/// <summary>
		/// Unique identifier of the user who last modified the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}

		/// <summary>
		/// Date and time when the solution was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}

		/// <summary>
		/// Unique identifier of the delegate user who modified the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}

		/// <summary>
		/// Unique identifier of the organization associated with the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}

		/// <summary>
		/// Unique identifier of the parent solution. Should only be non-null if this solution is a patch.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentsolutionid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentSolutionId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentsolutionid");
			}
		}

		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pinpointassetid")]
		public string PinpointAssetId
		{
			get
			{
				return this.GetAttributeValue<string>("pinpointassetid");
			}
		}

		/// <summary>
		/// Identifier of the publisher of this solution in Microsoft Pinpoint.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pinpointpublisherid")]
		public System.Nullable<long> PinpointPublisherId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("pinpointpublisherid");
			}
		}

		/// <summary>
		/// Default locale of the solution in Microsoft Pinpoint.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pinpointsolutiondefaultlocale")]
		public string PinpointSolutionDefaultLocale
		{
			get
			{
				return this.GetAttributeValue<string>("pinpointsolutiondefaultlocale");
			}
		}

		/// <summary>
		/// Identifier of the solution in Microsoft Pinpoint.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pinpointsolutionid")]
		public System.Nullable<long> PinpointSolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("pinpointsolutionid");
			}
		}

		/// <summary>
		/// Unique identifier of the publisher.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publisherid")]
		public Microsoft.Xrm.Sdk.EntityReference PublisherId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("publisherid");
			}
			set
			{
				this.OnPropertyChanging("PublisherId");
				this.SetAttributeValue("publisherid", value);
				this.OnPropertyChanged("PublisherId");
			}
		}

		/// <summary>
		/// Unique identifier of the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
			set
			{
				this.OnPropertyChanging("SolutionId");
				this.SetAttributeValue("solutionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("SolutionId");
			}
		}

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SolutionId = value;
			}
		}

		/// <summary>
		/// Solution package source organization version
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionpackageversion")]
		public string SolutionPackageVersion
		{
			get
			{
				return this.GetAttributeValue<string>("solutionpackageversion");
			}
			set
			{
				this.OnPropertyChanging("SolutionPackageVersion");
				this.SetAttributeValue("solutionpackageversion", value);
				this.OnPropertyChanged("SolutionPackageVersion");
			}
		}

		/// <summary>
		/// Solution Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutiontype")]
		public System.Nullable<EarlyBoundSolutionGenerator.solution_solutiontype> SolutionType
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("solutiontype");
				if ((optionSet != null))
				{
					return ((EarlyBoundSolutionGenerator.solution_solutiontype)(System.Enum.ToObject(typeof(EarlyBoundSolutionGenerator.solution_solutiontype), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("SolutionType");
				if ((value == null))
				{
					this.SetAttributeValue("solutiontype", null);
				}
				else
				{
					this.SetAttributeValue("solutiontype", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("SolutionType");
			}
		}

		/// <summary>
		/// The unique name of this solution
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return this.GetAttributeValue<string>("uniquename");
			}
			set
			{
				this.OnPropertyChanging("UniqueName");
				this.SetAttributeValue("uniquename", value);
				this.OnPropertyChanged("UniqueName");
			}
		}

		/// <summary>
		/// Date and time when the solution was updated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updatedon")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("updatedon");
			}
		}

		/// <summary>
		/// Solution version, used to identify a solution for upgrades and hotfixes.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("version")]
		public string Version
		{
			get
			{
				return this.GetAttributeValue<string>("version");
			}
			set
			{
				this.OnPropertyChanging("Version");
				this.SetAttributeValue("version", value);
				this.OnPropertyChanged("Version");
			}
		}

		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}

		/// <summary>
		/// 1:N solution_parent_solution
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solution_parent_solution", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<EarlyBoundSolutionGenerator.Solution> Referencedsolution_parent_solution
		{
			get
			{
				return this.GetRelatedEntities<EarlyBoundSolutionGenerator.Solution>("solution_parent_solution", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencedsolution_parent_solution");
				this.SetRelatedEntities<EarlyBoundSolutionGenerator.Solution>("solution_parent_solution", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedsolution_parent_solution");
			}
		}

		/// <summary>
		/// 1:N solution_solutioncomponent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solution_solutioncomponent")]
		public System.Collections.Generic.IEnumerable<EarlyBoundSolutionGenerator.SolutionComponent> solution_solutioncomponent
		{
			get
			{
				return this.GetRelatedEntities<EarlyBoundSolutionGenerator.SolutionComponent>("solution_solutioncomponent", null);
			}
			set
			{
				this.OnPropertyChanging("solution_solutioncomponent");
				this.SetRelatedEntities<EarlyBoundSolutionGenerator.SolutionComponent>("solution_solutioncomponent", null, value);
				this.OnPropertyChanged("solution_solutioncomponent");
			}
		}

		/// <summary>
		/// N:1 solution_parent_solution
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentsolutionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solution_parent_solution", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public EarlyBoundSolutionGenerator.Solution Referencingsolution_parent_solution
		{
			get
			{
				return this.GetRelatedEntity<EarlyBoundSolutionGenerator.Solution>("solution_parent_solution", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
	}

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum solutioncomponent_rootcomponentbehavior
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncludeSubcomponents = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donotincludesubcomponents = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncludeAsShellOnly = 2,
	}

	/// <summary>
	/// A component of a CRM solution.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("solutioncomponent")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class SolutionComponent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{

		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SolutionComponent() :
				base(EntityLogicalName)
		{
		}

		public const string EntityLogicalName = "solutioncomponent";

		public const int EntityTypeCode = 7103;

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}

		/// <summary>
		/// The object type code of the component.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componenttype")]
		public System.Nullable<EarlyBoundSolutionGenerator.componenttype> ComponentType
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("componenttype");
				if ((optionSet != null))
				{
					return ((EarlyBoundSolutionGenerator.componenttype)(System.Enum.ToObject(typeof(EarlyBoundSolutionGenerator.componenttype), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
		}

		/// <summary>
		/// Unique identifier of the user who created the solution
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}

		/// <summary>
		/// Date and time when the solution was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}

		/// <summary>
		/// Unique identifier of the delegate user who created the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}

		/// <summary>
		/// Indicates whether this component is metadata or data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismetadata")]
		public System.Nullable<bool> IsMetadata
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismetadata");
			}
		}

		/// <summary>
		/// Unique identifier of the user who last modified the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}

		/// <summary>
		/// Date and time when the solution was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}

		/// <summary>
		/// Unique identifier of the delegate user who modified the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}

		/// <summary>
		/// Unique identifier of the object with which the component is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public System.Nullable<System.Guid> ObjectId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("objectid");
			}
		}

		/// <summary>
		/// Indicates the include behavior of the root component.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rootcomponentbehavior")]
		public System.Nullable<EarlyBoundSolutionGenerator.solutioncomponent_rootcomponentbehavior> RootComponentBehavior
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("rootcomponentbehavior");
				if ((optionSet != null))
				{
					return ((EarlyBoundSolutionGenerator.solutioncomponent_rootcomponentbehavior)(System.Enum.ToObject(typeof(EarlyBoundSolutionGenerator.solutioncomponent_rootcomponentbehavior), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
		}

		/// <summary>
		/// The parent ID of the subcomponent, which will be a root
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rootsolutioncomponentid")]
		public System.Nullable<System.Guid> RootSolutionComponentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("rootsolutioncomponentid");
			}
		}

		/// <summary>
		/// Unique identifier of the solution component.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutioncomponentid")]
		public System.Nullable<System.Guid> SolutionComponentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutioncomponentid");
			}
		}

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutioncomponentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}

		/// <summary>
		/// Unique identifier of the solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public Microsoft.Xrm.Sdk.EntityReference SolutionId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("solutionid");
			}
		}

		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}

		/// <summary>
		/// 1:N solutioncomponent_parent_solutioncomponent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponent_parent_solutioncomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<EarlyBoundSolutionGenerator.SolutionComponent> Referencedsolutioncomponent_parent_solutioncomponent
		{
			get
			{
				return this.GetRelatedEntities<EarlyBoundSolutionGenerator.SolutionComponent>("solutioncomponent_parent_solutioncomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencedsolutioncomponent_parent_solutioncomponent");
				this.SetRelatedEntities<EarlyBoundSolutionGenerator.SolutionComponent>("solutioncomponent_parent_solutioncomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedsolutioncomponent_parent_solutioncomponent");
			}
		}

		/// <summary>
		/// N:1 solution_solutioncomponent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solution_solutioncomponent")]
		public EarlyBoundSolutionGenerator.Solution solution_solutioncomponent
		{
			get
			{
				return this.GetRelatedEntity<EarlyBoundSolutionGenerator.Solution>("solution_solutioncomponent", null);
			}
		}

		/// <summary>
		/// N:1 solutioncomponent_parent_solutioncomponent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rootsolutioncomponentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponent_parent_solutioncomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public EarlyBoundSolutionGenerator.SolutionComponent Referencingsolutioncomponent_parent_solutioncomponent
		{
			get
			{
				return this.GetRelatedEntity<EarlyBoundSolutionGenerator.SolutionComponent>("solutioncomponent_parent_solutioncomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
	}

	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class OrganizationServiceContext1 : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{

		/// <summary>
		/// Constructor.
		/// </summary>
		public OrganizationServiceContext1(Microsoft.Xrm.Sdk.IOrganizationService service) :
				base(service)
		{
		}

		/// <summary>
		/// Gets a binding to the set of all <see cref="EarlyBoundSolutionGenerator.Solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<EarlyBoundSolutionGenerator.Solution> SolutionSet
		{
			get
			{
				return this.CreateQuery<EarlyBoundSolutionGenerator.Solution>();
			}
		}

		/// <summary>
		/// Gets a binding to the set of all <see cref="EarlyBoundSolutionGenerator.SolutionComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<EarlyBoundSolutionGenerator.SolutionComponent> SolutionComponentSet
		{
			get
			{
				return this.CreateQuery<EarlyBoundSolutionGenerator.SolutionComponent>();
			}
		}
	}
}
