name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
          useConfigFile: true
          configFilePath: ./GitVersion.yml

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore EarlyXrm.EarlyBoundGenerator.sln
      
    - name: Build
      run: msbuild EarlyXrm.EarlyBoundGenerator.sln /p:Configuration=Release

    - name: Test
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Pack EarlyXrm.EarlyBoundGenerator
      run: msbuild -t:pack EarlyXrm.EarlyBoundGenerator\EarlyXrm.EarlyBoundGenerator.csproj /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
      
