name: CI

on:
  push:
    branches:
     - '**'
    tags:
     - 'v*.*.*'
  pull_request:
    branches:
     - '**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
          useConfigFile: true
          configFilePath: ./GitVersion.yml

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1  
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore EarlyXrm.EarlyBoundGenerator.sln
      
    - name: Build
      run: msbuild EarlyXrm.EarlyBoundGenerator.sln /p:Configuration=Release

    - name: vstest-solution-action
      uses: tonyhallett/vstest-solution-action@v1.0.0
      with:
        solution: EarlyXrm.EarlyBoundGenerator.sln

    - name: Pack EarlyXrm.EarlyBoundGenerator
      run: nuget pack EarlyXrm.EarlyBoundGenerator\EarlyXrm.EarlyBoundGenerator.nuspec -Version ${{ steps.gitversion.outputs.NuGetVersionV2 }} -properties Configuration=Release

    - name: Publish build artifacts
      uses: actions/upload-artifact@master
      with:
        name: packages
        path: ./**/EarlyXrm.EarlyBoundGenerator.*.nupkg

    - name: Add Github Source
      run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -Username ${{ github.repository_owner }} -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Remove package versions
      id: remove-package-versions
      uses: epitomeglobal/remove-package-versions@master
      with:
        keep-versions: 2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to github
      run: nuget push **/EarlyXrm.EarlyBoundGenerator.*.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -SkipDuplicate

    - name: Push to nuget.org
      run: nuget push **/EarlyXrm.EarlyBoundGenerator.*.nupkg -ApiKey ${{ secrets.NUGET_APIKEY }} -source https://api.nuget.org/v3/index.json
